### ISSUE TITLE
Error on HA 2024.5.2

### ISSUE THREAD

**Issue by tanker11** [constructorfleet/HomeAssistant-Component-OpenAIOverride#6]
Hello,

Still using your idea in my home - not sure how and when the embedded assistant will be enough intelligent to answer my questions. :)

Now, after upgrading to 2024.5.2 I have the following error:
------------
Error during setup of component openai_override
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/openai_override/__init__.py", line 34, in async_setup
    from homeassistant.components.openai_conversation import OpenAIAgent
ImportError: cannot import name 'OpenAIAgent' from 'homeassistant.components.openai_conversation' (/usr/src/homeassistant/homeassistant/components/openai_conversation/__init__.py)
------------

Is it something you could look into please?
